title: "A Human Lobster"
author: "Lobsterx"
description: "A place to upload my mind"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About", icon: name card}
  - {file: "Archive.md", title: "Archive", icon: archive}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Mail, icon: envelope, url: "mailto:lobstersister@protonmail.com"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/ahumanlobster/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/a_human_lobster"}
  - {title: Substack, icon: blog, url: "https://meishaonvzhanshi.substack.com"}
     

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
