title: "A Human Lobster"
author: "Lobsterx"
description: "I write to upload my mind"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "home change"}
  - {file: "README.md", title: "about me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "lobstersister@protonmail.com"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/ahumanlobster/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/a_human_lobster"}
  - {title: Substack, icon: substack, url: ""}
     

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
